### ISSUE TITLE
A couple of errors in KeyVault project while compiling

### ISSUE THREAD

**Issue by c-arnab** [mspnp/multitenant-saas-guidance#101]
I'm getting two errors in KeyVaultConfigurationProvider.cs file in line 111..

`foreach (var secretItem in secretsResponseList.Value ?? new List<SecretItem>())`

a) 'IPage<SecretItem>' does not contain a definition for 'Value' and no extension method 'Value' accepting a first argument of type 'IPage<SecretItem>' could be found (are you missing a using directive or an assembly reference?)	

b)The type or namespace name 'SecretItem' could not be found (are you missing a using directive or an assembly reference?)
The second error seems to go away if I add namespace Microsoft.Azure.KeyVault.Models in using list

I'm using visual studio 2017 community to compile

Thanks

**Comment by atoakley** [comment]
This is a known issue.  We are currently in the process of updating the project to 2017.  It should be done in the next couple of weeks.
