### ISSUE TITLE
Token caching question?

### ISSUE THREAD

**Issue by dmcweeney** [mspnp/multitenant-saas-guidance#102]
I was under the impression that the token cache would need to persist to some form of storage. 
If the redis cache is memory only (Basic C0) and crashes or is restarted - is the web app not out of sync with the cache and would need to be restarted too, to force users to relogin to get their authorization code/tokens.

Thanks

Donal

**Comment by jocontr** [comment]
If I understand your questions correctly; you may referring to an on-premise strategy. If that is the case there are various caching strategies you could deploy to accommodate your needs. In this particular guidance we are leveraging Azure AD which covers the most common resiliency scenarios.
