### ISSUE TITLE
Port to .Net Core 2

### ISSUE THREAD

**Issue by tnsholding** [mspnp/multitenant-saas-guidance#104]
Trying to make a multi-tenant app with a web api using Delegated user identity as in this guidance. But I need to do it in .Net Core 2, and a lot has changed in the authentication part from 1.x to 2 release.

Any plans on porting this guidance to .Net Core 2?
Or any good recommandations for other ressources to set this up - does not seem to be a lot of documentation available about this yet.

**Comment by premaarya** [comment]
Looking for the same info.

**Comment by manikandanramaswami** [comment]
Any update/plans to update this to .net core 2.2/3.0 framework?

**Comment by hagh** [comment]
It is very difficult to follow the guideline with all the changes to both Azure portal UI and .Net Core.

**Comment by josevarela** [comment]
This issue has been resolved with PR [112](https://github.com/mspnp/multitenant-saas-guidance/pull/112), which upgrades the solution to .NET Core 3.1
