### ISSUE TITLE
Run sample on VS2017 15.9

### ISSUE THREAD

**Issue by misirlou-tg** [mspnp/multitenant-saas-guidance#107]
When I attempt to create the local database with the 'dotnet ef' command I get the following error:

`Startup project 'Tailspin.Surveys.Web.csproj' targets framework '.NETCoreApp' version '1.1'. This version of the Entity Framework Core .NET Command-line Tools only supports version 2.0 or higher. For information on using older versions of the tools, see https://go.microsoft.com/fwlink/?linkid=871254`

When I try to use older versions of the tools I get more/different errors. Is is possible to run this sample anymore before it is ported to .NET Core 2?

**Comment by josevarela** [comment]
With PR [112 ](https://github.com/mspnp/multitenant-saas-guidance/pull/112)the solution has been ported to .NET Core 3.1 and should work with more recent versions of Visual Studio. Please re-test and let us know if you continue to experience issues
