### ISSUE TITLE
I think it should use AddDistributedMemoryCache(IServiceCollection) instead as the current code will inject dependency for IMemoryCache not IDistributedCache

### ISSUE THREAD

**Issue by ikmoss** [mspnp/multitenant-saas-guidance#110]
https://github.com/mspnp/multitenant-saas-guidance/blob/7daf61e34e8cf7028fc742f632a98ce8d4a2c7e3/src/Tailspin.Surveys.Web/Startup.cs#L78

**Comment by josevarela** [comment]
This issue has been corrected in PR [112 ](https://github.com/mspnp/multitenant-saas-guidance/pull/112). The call to AddMemoryCache(); was redundant and has been removed
