### ISSUE TITLE
AADSTS54005: OAuth2 Authorization code was already redeemed

### ISSUE THREAD

**Issue by fabiosaloni** [mspnp/multitenant-saas-guidance#111]
When I try to register a new tenant I keep receiving the following error message from AD:

OpenIdConnectProtocolException: Message contains error: 'invalid_grant', error_description: 'AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.

It seems this is due to changes in AD that have not been reflected in this applications. See this [blog](https://social.msdn.microsoft.com/Forums/en-US/4192e141-309a-4dd6-a5c9-f1a8ce32f4ca/aadsts54005-oauth2-authorization-code-was-already-redeemed?forum=WindowsAzureAD):

**Comment by josevarela** [comment]
This issue should be resolved with PR [112](https://github.com/mspnp/multitenant-saas-guidance/pull/112). Please verify and let us know if see this issue happening again.
