### ISSUE TITLE
Tenant enrollment fails

### ISSUE THREAD

**Issue by frits-lassche** [mspnp/multitenant-saas-guidance#113]
We tried to get the Tailspin example running. Cause we are trying to make a multi tenant SAAS application and the Tailspin example seems like a good starting point for the authentication part.

Running the example gives the following exception when trying to get a tenant enrolled:

AdalServiceException: AADSTS90008: The user or administrator has not consented to use the application with ID 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx'(Surveys). This happened because application is misconfigured: it must require access to Microsoft Graph by specifying at least 'Sign in and read user profile' permission.

![Exception](https://user-images.githubusercontent.com/66119006/83258242-372c6e80-a1b6-11ea-92cc-313bd4173d9e.png)

But we did get the consent window and accepted. In the enterprice-applications we can even see both the Surveys and the Surveys-WebAPI have consent for all the required API's

![consent](https://user-images.githubusercontent.com/66119006/83258320-56c39700-a1b6-11ea-8de0-2216c6bc9b8a.png)
![Permissions Survey Web](https://user-images.githubusercontent.com/66119006/83258288-49a6a800-a1b6-11ea-8376-200fe1d2dd65.png)
![Permissions Survey WebApi](https://user-images.githubusercontent.com/66119006/83258292-4c090200-a1b6-11ea-850b-35cd145929bc.png)

The get-started.md seems a bit out-of-date. The GUI of azure has changed quite a bit. And to get the example to 'work' (till the point of this exception) we did some extra steps:
1. Added a scope to Surveys.WebAPI. To be able to add the Surveys.WebAPI to the API permissions of the Surveys application.
2. We had to add support for ID-tokens (implicit grant) to the Surveys application

![scope](https://user-images.githubusercontent.com/66119006/83258344-65aa4980-a1b6-11ea-8f04-cb4c8ae1cf6a.png)

We suspect something has changed in the Azure environment around the multi tenant authentication, which causes this exception. But we can't find out which setting or configuration we are missing. On the internet we did not find any clues that could help us.

Hopefully you can help us

Frits Lassche

**Comment by josevarela** [comment]
Thank you for the detailed report and the comments. We are aware that changes in the UI have made the instructions somewhat out of date and will be updating the instructions soon.

In your case, can you try authorizing the Web Application to access the scope you have defined in the WebAPI? Should be able to do so by selecting the "Add Client application" button shown in the last image of your initial comments.

![image](https://user-images.githubusercontent.com/1648509/83335893-d5cfd280-a27d-11ea-91e2-e71aa08b604d.png)

On the "Add a client application screen", add the Client ID of the Survey application, select the scope you've have previously defined, and select the "add application" button.

![image](https://user-images.githubusercontent.com/1648509/83336431-517f4e80-a281-11ea-96a6-9af92312a2d7.png)

Hopefully this would do the trick. Please let us know once you try it.

**Comment by frits-lassche** [comment]
Thanks for your quick response. This was an option we already had tried, with no success.

It turns out that our problem was misconfiguration in the client secrets of the Survey application. We filled in the URI of the Survey application in stead of the URI of the Survey.WebAPI as WebApiResourceId. This gave the for us strange fault responses (because the experience was missing), but now it makes more sense.
