### ISSUE TITLE
Executing in VS 2019 debugging appears to have several issues

### ISSUE THREAD

**Issue by jrroby** [mspnp/multitenant-saas-guidance#118]
I am curious if this has been run in VS 2019? When I run the program after filling out all prerequisites it appears to not load all required views. I also see issues with the actual theming of the site (not a big issue but seems to point to a larger issue of the site not fully functional). Before I start diving into the issues I am seeing, I just want to make sure I am not missing something larger that will address several of the issues I am seeing. Most of the Nuget packages are running on 3.1.4 which are far behind the 5.X.X versions currently out.

**Comment by magrande** [comment]
@jrroby  Thank you for raising this issue. We are working on the theming issue, which is related to some migration from bower to libman, we still need to do. We'll keep you updated

**Comment by magrande** [comment]
A fix for this problem is going to be live soon. I'm going to close this issue. Thanks for reporting it.
